### ISSUE TITLE
Request for a way to easily filter per expansion

### ISSUE THREAD

**Issue by martinboy1974** [GurliGebis/AngrierWorldQuests#9]
I just tried your version of the angry world quest addon and I like it so far. I just wish that there was a way to filter per expansion.

Like if I enable all the filters, only the filter icons relevant for the current zone shows in the questlog. That would be great. Or else there are so many different filter icons showing in the questlog no matter what zone I am in.

The filter icons in the questlog also covers the World Quests name, so maybe move the line of filter icons under the World Quest name.

**Comment by GurliGebis** [comment]
I like that idea, I'm in the process of leveling to 60, so I can work on it with Shadowlands world quests.

**Comment by GurliGebis** [comment]
@martinboy1974 I have been thinking about this for a while. I see one issue that I cannot think of a great solution to.
If for instance a user filter on war resources, and then changes the map to shadowlands, where war resources does not exist, the filter button would be missing, but the filter is still set. 
So how should it handle this - if we clear the filter, then what to do, when going back to the BFA map? (since it was cleared automatically) 

Any ideas? 🙂

**Comment by martinboy1974** [comment]
Take a look at the addon World Quest Tab. They have added a filter button to the world map. That way the small filter icons could be skipped and just use a filter button on the world map to set filters on the go. The filter buttons are kind in the way, because there can be so many, if all filters are activated. That could be one way to do it.

**Comment by GurliGebis** [comment]
I'll take a look at it

**Comment by martinboy1974** [comment]
If u feel its too much work, then World Quest Tab is also a fine replacement with a lot of settings.

**Comment by GurliGebis** [comment]
I don't think that, though I haven't really have time to take a look at it yet, since I think it will require a bit of a rewrite of the filtering logic :)

**Comment by GurliGebis** [comment]
Fixed in version 0.33.0
